spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    databasePlatform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddlAuto: create
  h2:
    console:
      enabled: true
      path: /h2-console

